/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.qlcovid;

import javax.swing.*;

/**
 *
 * @author nhonnhon
 */
public class ManagerUI extends javax.swing.JFrame {
    /**
     * Creates new form ManagerUI
     */
    public ManagerUI() {
        initComponents();
        this.setSize(1600,900);
        this.setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpn_main = new javax.swing.JPanel();
        jpn_left = new javax.swing.JPanel();
        jlb_tabname = new javax.swing.JLabel();
        jpn_table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_func2 = new javax.swing.JButton();
        btn_func1 = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        jpn_right1 = new javax.swing.JPanel();
        jpn_right = new javax.swing.JPanel();
        jlb_search = new javax.swing.JLabel();
        cb_search = new javax.swing.JComboBox<>();
        cb_key = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        btn_searchmore = new javax.swing.JButton();
        jlb_sort = new javax.swing.JLabel();
        cb_sort = new javax.swing.JComboBox<>();
        btn_sortmore = new javax.swing.JButton();
        btn_sort = new javax.swing.JButton();
        jlb_view = new javax.swing.JLabel();
        btn_view_cancel = new javax.swing.JButton();
        btn_view_down = new javax.swing.JButton();
        btn_view_up = new javax.swing.JButton();
        jmb1 = new javax.swing.JMenuBar();
        jmn1 = new javax.swing.JMenu();
        jmi1 = new javax.swing.JMenuItem();
        jmi2 = new javax.swing.JMenuItem();
        jmn2 = new javax.swing.JMenu();
        jmn3 = new javax.swing.JMenu();
        jmi4 = new javax.swing.JMenuItem();
        jmi5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Covid Management");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(3000, 1800));
        setMinimumSize(new java.awt.Dimension(1040, 440));
        setPreferredSize(new java.awt.Dimension(1600, 900));
        setResizable(false);

        jpn_main.setBackground(new java.awt.Color(204, 204, 204));

        jpn_left.setBackground(new java.awt.Color(255, 255, 255));

        jlb_tabname.setBackground(new java.awt.Color(204, 204, 204));
        jlb_tabname.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jlb_tabname.setForeground(new java.awt.Color(102, 102, 102));
        jlb_tabname.setText("Covid Management");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(51, 51, 51));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setForeground(new java.awt.Color(102, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setDragEnabled(true);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jpn_tableLayout = new javax.swing.GroupLayout(jpn_table);
        jpn_table.setLayout(jpn_tableLayout);
        jpn_tableLayout.setHorizontalGroup(
            jpn_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jpn_tableLayout.setVerticalGroup(
            jpn_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        btn_func2.setBackground(new java.awt.Color(102, 102, 102));
        btn_func2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_func2.setForeground(new java.awt.Color(255, 255, 255));
        btn_func2.setText("Statistical system");

        btn_func1.setBackground(new java.awt.Color(102, 102, 102));
        btn_func1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_func1.setForeground(new java.awt.Color(255, 255, 255));
        btn_func1.setText("Neccessary items");

        btn_add.setBackground(new java.awt.Color(51, 51, 51));
        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_add.setForeground(new java.awt.Color(204, 204, 204));
        btn_add.setText("Add");

        btn_update.setBackground(new java.awt.Color(51, 51, 51));
        btn_update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_update.setForeground(new java.awt.Color(204, 204, 204));
        btn_update.setText("Update");

        btn_remove.setBackground(new java.awt.Color(51, 51, 51));
        btn_remove.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_remove.setForeground(new java.awt.Color(204, 204, 204));
        btn_remove.setText("Remove");

        javax.swing.GroupLayout jpn_leftLayout = new javax.swing.GroupLayout(jpn_left);
        jpn_left.setLayout(jpn_leftLayout);
        jpn_leftLayout.setHorizontalGroup(
            jpn_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_leftLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jpn_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpn_leftLayout.createSequentialGroup()
                        .addComponent(btn_remove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_add))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpn_leftLayout.createSequentialGroup()
                        .addComponent(btn_func1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_func2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jlb_tabname))
                    .addComponent(jpn_table, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        jpn_leftLayout.setVerticalGroup(
            jpn_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_leftLayout.createSequentialGroup()
                .addGroup(jpn_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpn_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_func1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_func2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlb_tabname, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpn_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpn_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jpn_right1.setBackground(new java.awt.Color(51, 51, 51));

        jpn_right.setBackground(new java.awt.Color(255, 255, 255));

        jlb_search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlb_search.setForeground(new java.awt.Color(102, 102, 102));
        jlb_search.setText("Search");

        cb_search.setBackground(new java.awt.Color(255, 255, 255));
        cb_search.setForeground(new java.awt.Color(102, 102, 102));
        cb_search.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cb_key.setBackground(new java.awt.Color(255, 255, 255));
        cb_key.setForeground(new java.awt.Color(102, 102, 102));
        cb_key.setText("keyword");

        btn_search.setBackground(new java.awt.Color(102, 102, 102));
        btn_search.setForeground(new java.awt.Color(204, 204, 204));
        btn_search.setText("Search");

        btn_searchmore.setBackground(new java.awt.Color(102, 102, 102));
        btn_searchmore.setForeground(new java.awt.Color(204, 204, 204));
        btn_searchmore.setText("...");

        jlb_sort.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlb_sort.setForeground(new java.awt.Color(102, 102, 102));
        jlb_sort.setText("Sort");

        cb_sort.setBackground(new java.awt.Color(255, 255, 255));
        cb_sort.setForeground(new java.awt.Color(102, 102, 102));
        cb_sort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_sortmore.setBackground(new java.awt.Color(102, 102, 102));
        btn_sortmore.setForeground(new java.awt.Color(204, 204, 204));
        btn_sortmore.setText("jButton9");

        btn_sort.setBackground(new java.awt.Color(102, 102, 102));
        btn_sort.setForeground(new java.awt.Color(204, 204, 204));
        btn_sort.setText("jButton8");

        jlb_view.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlb_view.setForeground(new java.awt.Color(102, 102, 102));
        jlb_view.setText("View related people");

        btn_view_cancel.setBackground(new java.awt.Color(102, 102, 102));
        btn_view_cancel.setForeground(new java.awt.Color(204, 204, 204));
        btn_view_cancel.setText("X");

        btn_view_down.setBackground(new java.awt.Color(102, 102, 102));
        btn_view_down.setForeground(new java.awt.Color(204, 204, 204));
        btn_view_down.setText("Down");

        btn_view_up.setBackground(new java.awt.Color(102, 102, 102));
        btn_view_up.setForeground(new java.awt.Color(204, 204, 204));
        btn_view_up.setText("Up");

        javax.swing.GroupLayout jpn_rightLayout = new javax.swing.GroupLayout(jpn_right);
        jpn_right.setLayout(jpn_rightLayout);
        jpn_rightLayout.setHorizontalGroup(
            jpn_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_rightLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpn_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jpn_rightLayout.createSequentialGroup()
                        .addComponent(btn_view_up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_view_down, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_view_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpn_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlb_search)
                        .addComponent(jlb_view)
                        .addComponent(jlb_sort)
                        .addComponent(cb_key, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpn_rightLayout.createSequentialGroup()
                            .addComponent(cb_search, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_searchmore, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpn_rightLayout.createSequentialGroup()
                            .addComponent(cb_sort, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_sort, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_sortmore, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jpn_rightLayout.setVerticalGroup(
            jpn_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_rightLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jlb_search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpn_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_search)
                    .addComponent(btn_searchmore)
                    .addComponent(cb_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlb_sort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpn_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_sort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sort)
                    .addComponent(btn_sortmore))
                .addGap(21, 21, 21)
                .addComponent(jlb_view)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpn_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_view_down)
                    .addComponent(btn_view_cancel)
                    .addComponent(btn_view_up))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpn_right1Layout = new javax.swing.GroupLayout(jpn_right1);
        jpn_right1.setLayout(jpn_right1Layout);
        jpn_right1Layout.setHorizontalGroup(
            jpn_right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_right1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpn_right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpn_right1Layout.setVerticalGroup(
            jpn_right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpn_right, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpn_mainLayout = new javax.swing.GroupLayout(jpn_main);
        jpn_main.setLayout(jpn_mainLayout);
        jpn_mainLayout.setHorizontalGroup(
            jpn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_mainLayout.createSequentialGroup()
                .addComponent(jpn_left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpn_right1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpn_mainLayout.setVerticalGroup(
            jpn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpn_left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpn_right1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jmn1.setText("File");

        jmi1.setText("Import New User");
        jmi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi1ActionPerformed(evt);
            }
        });
        jmn1.add(jmi1);

        jmi2.setText("Export database");
        jmn1.add(jmi2);

        jmb1.add(jmn1);

        jmn2.setText("Edit");
        jmb1.add(jmn2);

        jmn3.setText("Account");

        jmi4.setText("Manage account");
        jmn3.add(jmi4);

        jmi5.setText("Sign out");
        jmn3.add(jmi5);

        jmb1.add(jmn3);

        setJMenuBar(jmb1);
        jmb1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpn_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpn_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("jfrm");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void ManageUImain(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_func1;
    private javax.swing.JButton btn_func2;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_searchmore;
    private javax.swing.JButton btn_sort;
    private javax.swing.JButton btn_sortmore;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_view_cancel;
    private javax.swing.JButton btn_view_down;
    private javax.swing.JButton btn_view_up;
    private javax.swing.JTextField cb_key;
    private javax.swing.JComboBox<String> cb_search;
    private javax.swing.JComboBox<String> cb_sort;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlb_search;
    private javax.swing.JLabel jlb_sort;
    private javax.swing.JLabel jlb_tabname;
    private javax.swing.JLabel jlb_view;
    private javax.swing.JMenuBar jmb1;
    private javax.swing.JMenuItem jmi1;
    private javax.swing.JMenuItem jmi2;
    private javax.swing.JMenuItem jmi4;
    private javax.swing.JMenuItem jmi5;
    private javax.swing.JMenu jmn1;
    private javax.swing.JMenu jmn2;
    private javax.swing.JMenu jmn3;
    private javax.swing.JPanel jpn_left;
    private javax.swing.JPanel jpn_main;
    private javax.swing.JPanel jpn_right;
    private javax.swing.JPanel jpn_right1;
    private javax.swing.JPanel jpn_table;
    // End of variables declaration//GEN-END:variables
}
