/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.qlcovid.jframe;

/**
 *
 * @author nhonnhon
 */
public class Manager_statistics extends javax.swing.JPanel {

    /**
     * Creates new form Manager_statistics
     */
    public Manager_statistics() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        F0 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        p1num = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        F0toF1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        nopackage = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        p2num = new javax.swing.JLabel();
        p3num = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        snum1 = new javax.swing.JLabel();
        snum2 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();
        s3 = new javax.swing.JLabel();
        snum3 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        debt = new javax.swing.JLabel();
        F1 = new javax.swing.JLabel();
        F2 = new javax.swing.JLabel();
        F3 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        order = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Package");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Patient and related");

        F0.setBackground(new java.awt.Color(102, 102, 102));
        F0.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        F0.setForeground(new java.awt.Color(51, 51, 51));
        F0.setText("F0");

        jLabel16.setBackground(new java.awt.Color(102, 102, 102));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("F0");

        jLabel18.setBackground(new java.awt.Color(102, 102, 102));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("F0");

        jLabel22.setBackground(new java.awt.Color(102, 102, 102));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("province with the most cases");
        jLabel22.setToolTipText("");

        p1num.setBackground(new java.awt.Color(102, 102, 102));
        p1num.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        p1num.setForeground(new java.awt.Color(51, 51, 51));
        p1num.setText("F0");

        jLabel24.setBackground(new java.awt.Color(102, 102, 102));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("F0 to F1");
        jLabel24.setToolTipText("");

        F0toF1.setBackground(new java.awt.Color(102, 102, 102));
        F0toF1.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        F0toF1.setForeground(new java.awt.Color(51, 51, 51));
        F0toF1.setText("F0");

        jLabel26.setBackground(new java.awt.Color(102, 102, 102));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("number of packages");
        jLabel26.setToolTipText("");

        nopackage.setBackground(new java.awt.Color(102, 102, 102));
        nopackage.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        nopackage.setForeground(new java.awt.Color(51, 51, 51));
        nopackage.setText("F0");

        jLabel28.setBackground(new java.awt.Color(102, 102, 102));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("most sales");
        jLabel28.setToolTipText("");

        p2num.setBackground(new java.awt.Color(102, 102, 102));
        p2num.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        p2num.setForeground(new java.awt.Color(51, 51, 51));
        p2num.setText("F0");

        p3num.setBackground(new java.awt.Color(102, 102, 102));
        p3num.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        p3num.setForeground(new java.awt.Color(51, 51, 51));
        p3num.setText("F0");

        p1.setBackground(new java.awt.Color(102, 102, 102));
        p1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        p1.setForeground(new java.awt.Color(51, 51, 51));
        p1.setText("F0 to F1");
        p1.setToolTipText("");

        p2.setBackground(new java.awt.Color(102, 102, 102));
        p2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        p2.setForeground(new java.awt.Color(51, 51, 51));
        p2.setText("F0 to F1");
        p2.setToolTipText("");

        p3.setBackground(new java.awt.Color(102, 102, 102));
        p3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        p3.setForeground(new java.awt.Color(51, 51, 51));
        p3.setText("F0 to F1");
        p3.setToolTipText("");

        s1.setBackground(new java.awt.Color(102, 102, 102));
        s1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        s1.setForeground(new java.awt.Color(51, 51, 51));
        s1.setText("F0 to F1");
        s1.setToolTipText("");

        snum1.setBackground(new java.awt.Color(102, 102, 102));
        snum1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        snum1.setForeground(new java.awt.Color(51, 51, 51));
        snum1.setText("F0");

        snum2.setBackground(new java.awt.Color(102, 102, 102));
        snum2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        snum2.setForeground(new java.awt.Color(51, 51, 51));
        snum2.setText("F0");

        s2.setBackground(new java.awt.Color(102, 102, 102));
        s2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        s2.setForeground(new java.awt.Color(51, 51, 51));
        s2.setText("F0 to F1");
        s2.setToolTipText("");

        s3.setBackground(new java.awt.Color(102, 102, 102));
        s3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        s3.setForeground(new java.awt.Color(51, 51, 51));
        s3.setText("F0 to F1");
        s3.setToolTipText("");

        snum3.setBackground(new java.awt.Color(102, 102, 102));
        snum3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        snum3.setForeground(new java.awt.Color(51, 51, 51));
        snum3.setText("F0");

        jLabel43.setBackground(new java.awt.Color(102, 102, 102));
        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(51, 51, 51));
        jLabel43.setText("total debt");
        jLabel43.setToolTipText("");

        debt.setBackground(new java.awt.Color(102, 102, 102));
        debt.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        debt.setForeground(new java.awt.Color(51, 51, 51));
        debt.setText("F0");

        F1.setBackground(new java.awt.Color(102, 102, 102));
        F1.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        F1.setForeground(new java.awt.Color(51, 51, 51));
        F1.setText("F0");

        F2.setBackground(new java.awt.Color(102, 102, 102));
        F2.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        F2.setForeground(new java.awt.Color(51, 51, 51));
        F2.setText("F0");

        F3.setBackground(new java.awt.Color(102, 102, 102));
        F3.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        F3.setForeground(new java.awt.Color(51, 51, 51));
        F3.setText("F0");

        jLabel48.setBackground(new java.awt.Color(102, 102, 102));
        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(51, 51, 51));
        jLabel48.setText("cured case");
        jLabel48.setToolTipText("");

        jLabel49.setBackground(new java.awt.Color(102, 102, 102));
        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(51, 51, 51));
        jLabel49.setText("F0");

        jLabel50.setBackground(new java.awt.Color(102, 102, 102));
        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(51, 51, 51));
        jLabel50.setText("F0");
        jLabel50.setToolTipText("");

        jLabel51.setBackground(new java.awt.Color(102, 102, 102));
        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(51, 51, 51));
        jLabel51.setText("F1");
        jLabel51.setToolTipText("");

        jLabel52.setBackground(new java.awt.Color(102, 102, 102));
        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(51, 51, 51));
        jLabel52.setText("F2");
        jLabel52.setToolTipText("");

        jLabel53.setBackground(new java.awt.Color(102, 102, 102));
        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(51, 51, 51));
        jLabel53.setText("F3");
        jLabel53.setToolTipText("");

        jLabel44.setBackground(new java.awt.Color(102, 102, 102));
        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(51, 51, 51));
        jLabel44.setText("total order");
        jLabel44.setToolTipText("");

        order.setBackground(new java.awt.Color(102, 102, 102));
        order.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        order.setForeground(new java.awt.Color(51, 51, 51));
        order.setText("F0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(F0)
                                                    .addComponent(jLabel50))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel51)
                                            .addComponent(F1))
                                        .addGap(28, 28, 28))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(F0toF1)
                                            .addComponent(jLabel24))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel49)
                                            .addComponent(jLabel48)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel22))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(p1num)
                                        .addGap(18, 18, 18)
                                        .addComponent(p1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(p3num)
                                        .addGap(18, 18, 18)
                                        .addComponent(p3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(p2num)
                                        .addGap(18, 18, 18)
                                        .addComponent(p2)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(F2)
                                            .addComponent(jLabel52))
                                        .addGap(106, 106, 106)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(F3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel26))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel53)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(nopackage))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(473, 473, 473)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(s1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(s2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(s3, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(snum1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(snum2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(snum3, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel28))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(debt, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel44)
                                    .addComponent(order))))))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(F0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel50)
                            .addComponent(jLabel51)
                            .addComponent(jLabel52)
                            .addComponent(jLabel53)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nopackage, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F0toF1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel48)
                            .addComponent(jLabel24)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(debt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(order, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(snum1)
                            .addComponent(s1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(snum2)
                            .addComponent(s2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(snum3)
                            .addComponent(s3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p1num)
                            .addComponent(p1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p2num)
                            .addComponent(p2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p3num)
                            .addComponent(p3))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel F0;
    private javax.swing.JLabel F0toF1;
    private javax.swing.JLabel F1;
    private javax.swing.JLabel F2;
    private javax.swing.JLabel F3;
    private javax.swing.JLabel debt;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel nopackage;
    private javax.swing.JLabel order;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p1num;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p2num;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p3num;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel s3;
    private javax.swing.JLabel snum1;
    private javax.swing.JLabel snum2;
    private javax.swing.JLabel snum3;
    // End of variables declaration//GEN-END:variables
}
